erichard_glide_resize:
    path:     /{server}/{path}
    defaults: { _controller: Erichard\Bundle\GlideBundle\Controller\GlideController::resize }
    methods: [GET]
    requirements:
        path: ".+"
